### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 171: character maps to <undefined>

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#10]
I did get this traceback error today with the updated version. 

Traceback (most recent call last):
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 635, in <module>
    asyncio.run(main())
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 599, in main
    results = await asyncio.gather(*tasks)
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 519, in download_images
    sort_images_by_model_name(dir_name)
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 190, in sort_images_by_model_name
    lines = file.readlines()
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 171: character maps to <undefined>

**Comment by Confuzu** [comment]
i have updated the script
