### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\uff0c' in position 4: character maps to <undefined> in tagnames.py

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#11]
I just ran tagnames.py with the latest version and got the below error. It was different enough I didn't want to just add it to the other issue. 

Traceback (most recent call last):
  File "X:\AI\Civitai Image Grabber\tagnames.py", line 51, in <module>
    process_data(items, file_path, read_existing_tag)
  File "X:\AI\Civitai Image Grabber\tagnames.py", line 30, in process_data
    file.write(name+ '\n')
  File "C:\Users\barre\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uff0c' in position 4: character maps to <undefined>

**Comment by Confuzu** [comment]
i  updated tagnames.py
