### ISSUE TITLE
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1007)

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#18]
Not sure if this was just a disconnection error, but it didn't match the last one and a bunch of other exceptions popped up also so figured I would post it in case. 

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\tls.py", line 131, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1007)

[2024-04-28 004729,807 - ERROR.txt](https://github.com/Confuzu/CivitAI_Image_grabber/files/15140813/2024-04-28.004729.807.-.ERROR.txt)

**Comment by Confuzu** [comment]
Thanks for posting, but  it's a network error between the script and the civitAI server. No script bug
