### ISSUE TITLE
UnboundLocalError: local variable 'model_dir' referenced before assignment

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#6]
I am getting the following error sometimes when attempting to download via model ID.  Nothing is downloaded and the folder isn't generated. This is also resulting I believe in loops being closed saying already visited even though I have nothing saved in the folder. 

Traceback (most recent call last):
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 370, in <module>
    asyncio.run(main())
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 352, in main
    results = await asyncio.gather(*tasks)
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 244, in download_images_for_model
    sort_images_by_model_name(model_dir)
UnboundLocalError: local variable 'model_dir' referenced before assignment

**Comment by Confuzu** [comment]
ok i'll take a look at it.

**Comment by Confuzu** [comment]
the Bug should be resolved
