### ISSUE TITLE
Traceback error after RemoteProtocolError: Server disconnected without sending a response.

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#7]
This popped up tonight when the server disconnected. I wish I could help, but I have zero python knowledge. Not sure if related to the other error. 

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 370, in <module>
    asyncio.run(main())
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 352, in main
    results = await asyncio.gather(*tasks)
  File "X:\AI\Civitai Image Grabber\civit_image_downloader.py", line 265, in download_images_for_username
    response = await client.get(url, timeout=timeout_value)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1801, in get
    return await self.request(
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by Confuzu** [comment]
The error message means that the script has sent a request  to the civit API  Server, but the server disconnected without sending a response back. It's an issue with the network or the server, not with the script it self.

**Comment by Nobrumski** [comment]
Ok good. I just figured I would report it in case. I know the API can be spotty.
